name: Prueba de docker push

on:
  workflow_dispatch:
  
  push:
    branches: [ "main" ]
    paths:
      - '**'

jobs:
  
  deploy:
    name: Previous steps
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Github Packages
        uses: docker/login-action@v1
        with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GHCR_PAT }}

      - name: Build image and push to GitHub Container Registry
        uses: docker/build-push-action@v2
        with:
            # relative path to the place where source code with Dockerfile is located
            context: ./
            # Note: tags has to be all lower-case
            tags: |
              ghcr.io/qbits-mx/dockerized-pruebita-goose:latest
            # build on feature branches, push only on main branch
            push: ${{ github.ref == 'refs/heads/main' }}
